# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('units', models.CharField(choices=[('кг', 'кг'), ('шт', 'шт'), ('л', 'л')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='jobtype',
            name='materials',
            field=models.ManyToManyField(to='api.Material'),
        ),
    ]
