# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
