# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171124_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='used_materials',
        ),
        migrations.AddField(
            model_name='usedmaterial',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_materials', to='api.Job'),
        ),
    ]
